// tslint:disable: object-literal-sort-keys
const MachineTypes = [
    {
        availableUsage: 60,
        cores: 16,
        lowPriorityCapable: true,
        maxDiskCount: 64,
        memory: 56.0,
        name: "Standard_DS5_v2",
        osDiskSize: 1023.0,
        price: 0.916,
        pricePerCore: 0.05725,
        resourceDiskSize: 112.0,
        sku: "DS5_v2",
        ssd: true,
        tier: "Standard",
        type: "General",
        usageLimit: 100
    },
    {
        name: "Standard_D4_v3",
        sku: "D4_v3",
        type: "General",
        tier: "Standard",
        cores: 4,
        memory: 16.0,
        maxDiskCount: 8,
        resourceDiskSize: 100.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 0.192,
        pricePerCore: 0.048,
        usageLimit: 10000,
        availableUsage: 5822,
    },
    {
        name: "Standard_E4s_v3",
        sku: "E4s_v3",
        type: "Memory",
        tier: "Standard",
        cores: 4,
        memory: 32.0,
        maxDiskCount: 8,
        resourceDiskSize: 64.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 0.252,
        pricePerCore: 0.063,
        usageLimit: 300,
        availableUsage: 300,
    },
    {
        name: "Standard_F2",
        sku: "F2",
        type: "Compute",
        tier: "Standard",
        cores: 2,
        memory: 4.0,
        maxDiskCount: 8,
        resourceDiskSize: 32.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 0.099,
        pricePerCore: 0.0495,
        usageLimit: 100,
        availableUsage: 100,
    },
    {
        name: "Standard_A3",
        sku: "A3",
        type: "General",
        tier: "Standard",
        cores: 4,
        memory: 7.0,
        maxDiskCount: 8,
        resourceDiskSize: 285.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 0.202,
        pricePerCore: 0.0505,
        usageLimit: 100,
        availableUsage: 94,
    },
    {
        name: "Standard_D15_v2",
        sku: "D15_v2",
        type: "Memory",
        tier: "Standard",
        cores: 20,
        memory: 140.0,
        maxDiskCount: 64,
        resourceDiskSize: 280.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 1.495,
        pricePerCore: 0.07475000000000001,
        usageLimit: 100,
        availableUsage: 76,
    },
    {
        name: "Standard_B2s",
        sku: "B2s",
        type: "General",
        tier: "Standard",
        cores: 2,
        memory: 4.0,
        maxDiskCount: 4,
        resourceDiskSize: 8.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: false,
        price: 0.0416,
        pricePerCore: 0.0208,
        usageLimit: 100,
        availableUsage: 100,
    },
    {
        name: "Standard_F4",
        sku: "F4",
        type: "Compute",
        tier: "Standard",
        cores: 4,
        memory: 8.0,
        maxDiskCount: 16,
        resourceDiskSize: 64.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 0.199,
        pricePerCore: 0.04975,
        usageLimit: 100,
        availableUsage: 100,
    },
    {
        name: "Standard_E64is_v3",
        sku: "E64is_v3",
        type: "Memory",
        tier: "Standard",
        cores: 64,
        memory: 432.0,
        maxDiskCount: 32,
        resourceDiskSize: 864.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 3.629,
        pricePerCore: 0.056703125,
        usageLimit: 100,
        availableUsage: 100,
    },
    {
        name: "Standard_D14_v2",
        sku: "D14_v2",
        type: "Memory",
        tier: "Standard",
        cores: 16,
        memory: 112.0,
        maxDiskCount: 64,
        resourceDiskSize: 800.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 1.196,
        pricePerCore: 0.07475,
        usageLimit: 100,
        availableUsage: 76,
    },
    {
        name: "Standard_E64s_v3",
        sku: "E64s_v3",
        type: "Memory",
        tier: "Standard",
        cores: 64,
        memory: 432.0,
        maxDiskCount: 32,
        resourceDiskSize: 864.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 3.629,
        pricePerCore: 0.056703125,
        usageLimit: 300,
        availableUsage: 300,
    },
    {
        name: "Standard_G1",
        sku: "G1",
        type: "Memory",
        tier: "Standard",
        cores: 2,
        memory: 28.0,
        maxDiskCount: 8,
        resourceDiskSize: 384.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 0.49,
        pricePerCore: 0.245,
        usageLimit: 100,
        availableUsage: 100,
    },
    {
        name: "Standard_NC24r",
        sku: "NC24r",
        type: "GPU",
        tier: "Standard",
        cores: 24,
        memory: 224.0,
        maxDiskCount: 64,
        resourceDiskSize: 1440.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 3.96,
        pricePerCore: 0.165,
        usageLimit: 48,
        availableUsage: 48,
    },
    {
        name: "Standard_B1ms",
        sku: "B1ms",
        type: "General",
        tier: "Standard",
        cores: 1,
        memory: 2.0,
        maxDiskCount: 2,
        resourceDiskSize: 4.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: false,
        price: 0.0208,
        pricePerCore: 0.0208,
        usageLimit: 100,
        availableUsage: 100,
    },
    {
        name: "Standard_F8",
        sku: "F8",
        type: "Compute",
        tier: "Standard",
        cores: 8,
        memory: 16.0,
        maxDiskCount: 32,
        resourceDiskSize: 128.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 0.398,
        pricePerCore: 0.04975,
        usageLimit: 100,
        availableUsage: 100,
    },
    {
        name: "Standard_E8-4s_v3",
        sku: "E8-4s_v3",
        type: "Memory",
        tier: "Standard",
        cores: 8,
        memory: 64.0,
        maxDiskCount: 16,
        resourceDiskSize: 128.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 0.504,
        pricePerCore: 0.063,
        usageLimit: 300,
        availableUsage: 300,
    },
    {
        name: "Standard_NC24rs_v2",
        sku: "NC24rs_v2",
        type: "GPU",
        tier: "Standard",
        cores: 24,
        memory: 448.0,
        maxDiskCount: 32,
        resourceDiskSize: 1344.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 9.108,
        pricePerCore: 0.3795,
        usageLimit: 0,
        availableUsage: 0,
    },
    {
        name: "Standard_D11_v2",
        sku: "D11_v2",
        type: "Memory",
        tier: "Standard",
        cores: 2,
        memory: 14.0,
        maxDiskCount: 8,
        resourceDiskSize: 100.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 0.149,
        pricePerCore: 0.0745,
        usageLimit: 100,
        availableUsage: 76,
    },
    {
        name: "Standard_M64-16ms",
        sku: "M64-16ms",
        type: "Memory",
        tier: "Standard",
        cores: 64,
        memory: 1750.0,
        maxDiskCount: 64,
        resourceDiskSize: 2000.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 10.337,
        pricePerCore: 0.161515625,
        usageLimit: 0,
        availableUsage: 0,
    },
    {
        name: "Standard_E64_v3",
        sku: "E64_v3",
        type: "Memory",
        tier: "Standard",
        cores: 64,
        memory: 432.0,
        maxDiskCount: 32,
        resourceDiskSize: 1600.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 3.629,
        pricePerCore: 0.056703125,
        usageLimit: 10000,
        availableUsage: 10000,
    },
    {
        name: "Standard_M32ls",
        sku: "M32ls",
        type: "Memory",
        tier: "Standard",
        cores: 32,
        memory: 256.0,
        maxDiskCount: 32,
        resourceDiskSize: 1000.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 2.873,
        pricePerCore: 0.08978125,
        usageLimit: 0,
        availableUsage: 0,
    },
    {
        name: "Standard_F72s_v2",
        sku: "F72s_v2",
        type: "Compute",
        tier: "Standard",
        cores: 72,
        memory: 144.0,
        maxDiskCount: 32,
        resourceDiskSize: 576.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 3.06,
        pricePerCore: 0.0425,
        usageLimit: 100,
        availableUsage: 100,
    },
    {
        name: "Standard_NC6s_v2",
        sku: "NC6s_v2",
        type: "GPU",
        tier: "Standard",
        cores: 6,
        memory: 112.0,
        maxDiskCount: 12,
        resourceDiskSize: 336.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 2.07,
        pricePerCore: 0.345,
        usageLimit: 0,
        availableUsage: 0,
    },
    {
        name: "Standard_A1",
        sku: "A1",
        type: "General",
        tier: "Standard",
        cores: 1,
        memory: 1.75,
        maxDiskCount: 2,
        resourceDiskSize: 70.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 0.051,
        pricePerCore: 0.051,
        usageLimit: 100,
        availableUsage: 94,
    },
    {
        name: "Standard_GS4",
        sku: "GS4",
        type: "Memory",
        tier: "Standard",
        cores: 16,
        memory: 224.0,
        maxDiskCount: 64,
        resourceDiskSize: 448.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 3.922,
        pricePerCore: 0.245125,
        usageLimit: 100,
        availableUsage: 100,
    },
    {
        name: "Standard_A4",
        sku: "A4",
        type: "General",
        tier: "Standard",
        cores: 8,
        memory: 14.0,
        maxDiskCount: 16,
        resourceDiskSize: 605.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 0.405,
        pricePerCore: 0.050625,
        usageLimit: 100,
        availableUsage: 94,
    },
    {
        name: "Standard_F32s_v2",
        sku: "F32s_v2",
        type: "Compute",
        tier: "Standard",
        cores: 32,
        memory: 64.0,
        maxDiskCount: 32,
        resourceDiskSize: 256.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 1.36,
        pricePerCore: 0.0425,
        usageLimit: 100,
        availableUsage: 100,
    },
    {
        name: "Standard_DS12-1_v2",
        sku: "DS12-1_v2",
        type: "General",
        tier: "Standard",
        cores: 4,
        memory: 28.0,
        maxDiskCount: 16,
        resourceDiskSize: 56.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 0.299,
        pricePerCore: 0.07475,
        usageLimit: 100,
        availableUsage: 60,
    },
    {
        name: "Standard_A0",
        sku: "A0",
        type: "General",
        tier: "Standard",
        cores: 1,
        memory: 0.75,
        maxDiskCount: 1,
        resourceDiskSize: 20.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: false,
        price: 0.02,
        pricePerCore: 0.02,
        usageLimit: 100,
        availableUsage: 94,
    },
    {
        name: "Basic_A0",
        sku: "A0",
        type: "General",
        tier: "Basic",
        cores: 1,
        memory: 0.75,
        maxDiskCount: 1,
        resourceDiskSize: 20.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: false,
        price: 0.018,
        pricePerCore: 0.018,
        usageLimit: 100,
        availableUsage: 100,
    },
    {
        name: "Standard_E32s_v3",
        sku: "E32s_v3",
        type: "Memory",
        tier: "Standard",
        cores: 32,
        memory: 256.0,
        maxDiskCount: 32,
        resourceDiskSize: 512.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 2.016,
        pricePerCore: 0.063,
        usageLimit: 300,
        availableUsage: 300,
    },
    {
        name: "Standard_NV6",
        sku: "NV6",
        type: "GPU",
        tier: "Standard",
        cores: 6,
        memory: 56.0,
        maxDiskCount: 24,
        resourceDiskSize: 380.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 1.093,
        pricePerCore: 0.18216666666666667,
        usageLimit: 24,
        availableUsage: 24,
    },
    {
        name: "Standard_D4s_v3",
        sku: "D4s_v3",
        type: "General",
        tier: "Standard",
        cores: 4,
        memory: 16.0,
        maxDiskCount: 8,
        resourceDiskSize: 32.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 0.192,
        pricePerCore: 0.048,
        usageLimit: 300,
        availableUsage: 278,
    },
    {
        name: "Standard_DS11-1_v2",
        sku: "DS11-1_v2",
        type: "General",
        tier: "Standard",
        cores: 2,
        memory: 14.0,
        maxDiskCount: 8,
        resourceDiskSize: 28.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 0.149,
        pricePerCore: 0.0745,
        usageLimit: 100,
        availableUsage: 60,
    },
    {
        name: "Standard_A2m_v2",
        sku: "A2m_v2",
        type: "General",
        tier: "Standard",
        cores: 2,
        memory: 16.0,
        maxDiskCount: 4,
        resourceDiskSize: 20.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 0.099,
        pricePerCore: 0.0495,
        usageLimit: 100,
        availableUsage: 100,
    },
    {
        name: "Standard_GS4-4",
        sku: "GS4-4",
        type: "Memory",
        tier: "Standard",
        cores: 16,
        memory: 224.0,
        maxDiskCount: 64,
        resourceDiskSize: 448.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 3.922,
        pricePerCore: 0.245125,
        usageLimit: 100,
        availableUsage: 100,
    },
    {
        name: "Standard_D12_v2",
        sku: "D12_v2",
        type: "Memory",
        tier: "Standard",
        cores: 4,
        memory: 28.0,
        maxDiskCount: 16,
        resourceDiskSize: 200.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 0.299,
        pricePerCore: 0.07475,
        usageLimit: 100,
        availableUsage: 76,
    },
    {
        name: "Basic_A3",
        sku: "A3",
        type: "General",
        tier: "Basic",
        cores: 4,
        memory: 7.0,
        maxDiskCount: 8,
        resourceDiskSize: 120.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 0.176,
        pricePerCore: 0.044,
        usageLimit: 100,
        availableUsage: 100,
    },
    {
        name: "Standard_NC24s_v3",
        sku: "NC24s_v3",
        type: "GPU",
        tier: "Standard",
        cores: 24,
        memory: 448.0,
        maxDiskCount: 32,
        resourceDiskSize: 1344.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 12.24,
        pricePerCore: 0.51,
        usageLimit: 0,
        availableUsage: 0,
    },
    {
        name: "Standard_E64i_v3",
        sku: "E64i_v3",
        type: "Memory",
        tier: "Standard",
        cores: 64,
        memory: 432.0,
        maxDiskCount: 32,
        resourceDiskSize: 1600.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 3.629,
        pricePerCore: 0.056703125,
        usageLimit: 100,
        availableUsage: 100,
    },
    {
        name: "Standard_E16s_v3",
        sku: "E16s_v3",
        type: "Memory",
        tier: "Standard",
        cores: 16,
        memory: 128.0,
        maxDiskCount: 32,
        resourceDiskSize: 256.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 1.008,
        pricePerCore: 0.063,
        usageLimit: 300,
        availableUsage: 300,
    },
    {
        name: "Standard_B4ms",
        sku: "B4ms",
        type: "General",
        tier: "Standard",
        cores: 4,
        memory: 16.0,
        maxDiskCount: 8,
        resourceDiskSize: 32.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: false,
        price: 0.166,
        pricePerCore: 0.0415,
        usageLimit: 100,
        availableUsage: 100,
    },
    {
        name: "Standard_D32s_v3",
        sku: "D32s_v3",
        type: "General",
        tier: "Standard",
        cores: 32,
        memory: 128.0,
        maxDiskCount: 32,
        resourceDiskSize: 256.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 1.536,
        pricePerCore: 0.048,
        usageLimit: 300,
        availableUsage: 278,
    },
    {
        name: "Standard_DS13_v2",
        sku: "DS13_v2",
        type: "Memory",
        tier: "Standard",
        cores: 8,
        memory: 56.0,
        maxDiskCount: 32,
        resourceDiskSize: 112.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 0.598,
        pricePerCore: 0.07475,
        usageLimit: 100,
        availableUsage: 60,
    },
    {
        name: "Standard_M64s",
        sku: "M64s",
        type: "Memory",
        tier: "Standard",
        cores: 64,
        memory: 1000.0,
        maxDiskCount: 64,
        resourceDiskSize: 2000.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 6.669,
        pricePerCore: 0.104203125,
        usageLimit: 0,
        availableUsage: 0,
    },
    {
        name: "Standard_M32-16ms",
        sku: "M32-16ms",
        type: "Memory",
        tier: "Standard",
        cores: 32,
        memory: 875.0,
        maxDiskCount: 32,
        resourceDiskSize: 1000.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 6.146,
        pricePerCore: 0.1920625,
        usageLimit: 0,
        availableUsage: 0,
    },
    {
        name: "Standard_DS15_v2",
        sku: "DS15_v2",
        type: "Memory",
        tier: "Standard",
        cores: 20,
        memory: 140.0,
        maxDiskCount: 64,
        resourceDiskSize: 280.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 1.495,
        pricePerCore: 0.07475000000000001,
        usageLimit: 100,
        availableUsage: 60,
    },
    {
        name: "Standard_B2ms",
        sku: "B2ms",
        type: "General",
        tier: "Standard",
        cores: 2,
        memory: 8.0,
        maxDiskCount: 4,
        resourceDiskSize: 16.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: false,
        price: 0.0832,
        pricePerCore: 0.0416,
        usageLimit: 100,
        availableUsage: 100,
    },
    {
        name: "Standard_ND6s",
        sku: "ND6s",
        type: "GPU",
        tier: "Standard",
        cores: 6,
        memory: 112.0,
        maxDiskCount: 12,
        resourceDiskSize: 336.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 2.07,
        pricePerCore: 0.345,
        usageLimit: 0,
        availableUsage: 0,
    },
    {
        name: "Standard_M32ms",
        sku: "M32ms",
        type: "Memory",
        tier: "Standard",
        cores: 32,
        memory: 875.0,
        maxDiskCount: 32,
        resourceDiskSize: 1000.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 6.146,
        pricePerCore: 0.1920625,
        usageLimit: 0,
        availableUsage: 0,
    },
    {
        name: "Standard_DS14_v2",
        sku: "DS14_v2",
        type: "Memory",
        tier: "Standard",
        cores: 16,
        memory: 112.0,
        maxDiskCount: 64,
        resourceDiskSize: 224.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 1.196,
        pricePerCore: 0.07475,
        usageLimit: 100,
        availableUsage: 60,
    },
    {
        name: "Standard_E16-8s_v3",
        sku: "E16-8s_v3",
        type: "Memory",
        tier: "Standard",
        cores: 16,
        memory: 128.0,
        maxDiskCount: 32,
        resourceDiskSize: 256.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 1.008,
        pricePerCore: 0.063,
        usageLimit: 300,
        availableUsage: 300,
    },
    {
        name: "Standard_F16s",
        sku: "F16s",
        type: "Compute",
        tier: "Standard",
        cores: 16,
        memory: 32.0,
        maxDiskCount: 64,
        resourceDiskSize: 64.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 0.796,
        pricePerCore: 0.04975,
        usageLimit: 100,
        availableUsage: 100,
    },
    {
        name: "Standard_B1s",
        sku: "B1s",
        type: "General",
        tier: "Standard",
        cores: 1,
        memory: 1.0,
        maxDiskCount: 2,
        resourceDiskSize: 2.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: false,
        price: 0.0104,
        pricePerCore: 0.0104,
        usageLimit: 100,
        availableUsage: 100,
    },
    {
        name: "Standard_D2s_v3",
        sku: "D2s_v3",
        type: "General",
        tier: "Standard",
        cores: 2,
        memory: 8.0,
        maxDiskCount: 4,
        resourceDiskSize: 16.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 0.096,
        pricePerCore: 0.048,
        usageLimit: 300,
        availableUsage: 278,
    },
    {
        name: "Standard_E16_v3",
        sku: "E16_v3",
        type: "Memory",
        tier: "Standard",
        cores: 16,
        memory: 128.0,
        maxDiskCount: 32,
        resourceDiskSize: 400.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 1.008,
        pricePerCore: 0.063,
        usageLimit: 10000,
        availableUsage: 10000,
    },
    {
        name: "Standard_NC12s_v3",
        sku: "NC12s_v3",
        type: "GPU",
        tier: "Standard",
        cores: 12,
        memory: 224.0,
        maxDiskCount: 24,
        resourceDiskSize: 672.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 6.12,
        pricePerCore: 0.51,
        usageLimit: 0,
        availableUsage: 0,
    },
    {
        name: "Standard_E2_v3",
        sku: "E2_v3",
        type: "Memory",
        tier: "Standard",
        cores: 2,
        memory: 16.0,
        maxDiskCount: 4,
        resourceDiskSize: 50.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 0.126,
        pricePerCore: 0.063,
        usageLimit: 10000,
        availableUsage: 10000,
    },
    {
        name: "Standard_F2s_v2",
        sku: "F2s_v2",
        type: "Compute",
        tier: "Standard",
        cores: 2,
        memory: 4.0,
        maxDiskCount: 4,
        resourceDiskSize: 16.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 0.085,
        pricePerCore: 0.0425,
        usageLimit: 100,
        availableUsage: 100,
    },
    {
        name: "Standard_DS13-2_v2",
        sku: "DS13-2_v2",
        type: "General",
        tier: "Standard",
        cores: 8,
        memory: 56.0,
        maxDiskCount: 32,
        resourceDiskSize: 112.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 0.598,
        pricePerCore: 0.07475,
        usageLimit: 100,
        availableUsage: 60,
    },
    {
        name: "Standard_F1s",
        sku: "F1s",
        type: "Compute",
        tier: "Standard",
        cores: 1,
        memory: 2.0,
        maxDiskCount: 4,
        resourceDiskSize: 4.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 0.05,
        pricePerCore: 0.05,
        usageLimit: 100,
        availableUsage: 100,
    },
    {
        name: "Standard_M8-2ms",
        sku: "M8-2ms",
        type: "Memory",
        tier: "Standard",
        cores: 8,
        memory: 218.75,
        maxDiskCount: 8,
        resourceDiskSize: 250.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 1.5365,
        pricePerCore: 0.1920625,
        usageLimit: 0,
        availableUsage: 0,
    },
    {
        name: "Standard_B8ms",
        sku: "B8ms",
        type: "General",
        tier: "Standard",
        cores: 8,
        memory: 32.0,
        maxDiskCount: 16,
        resourceDiskSize: 64.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: false,
        price: 0.333,
        pricePerCore: 0.041625,
        usageLimit: 100,
        availableUsage: 100,
    },
    {
        name: "Standard_M64",
        sku: "M64",
        type: "Memory",
        tier: "Standard",
        cores: 64,
        memory: 1000.0,
        maxDiskCount: 64,
        resourceDiskSize: 8000.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 6.669,
        pricePerCore: 0.104203125,
        usageLimit: 0,
        availableUsage: 0,
    },
    {
        name: "Standard_E32-16s_v3",
        sku: "E32-16s_v3",
        type: "Memory",
        tier: "Standard",
        cores: 32,
        memory: 256.0,
        maxDiskCount: 32,
        resourceDiskSize: 512.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 2.016,
        pricePerCore: 0.063,
        usageLimit: 300,
        availableUsage: 300,
    },
    {
        name: "Standard_DS14-8_v2",
        sku: "DS14-8_v2",
        type: "General",
        tier: "Standard",
        cores: 16,
        memory: 112.0,
        maxDiskCount: 64,
        resourceDiskSize: 224.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 1.196,
        pricePerCore: 0.07475,
        usageLimit: 100,
        availableUsage: 60,
    },
    {
        name: "Standard_DS1_v2",
        sku: "DS1_v2",
        type: "General",
        tier: "Standard",
        cores: 1,
        memory: 3.5,
        maxDiskCount: 4,
        resourceDiskSize: 7.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 0.057,
        pricePerCore: 0.057,
        usageLimit: 100,
        availableUsage: 60,
    },
    {
        name: "Standard_DS13-4_v2",
        sku: "DS13-4_v2",
        type: "General",
        tier: "Standard",
        cores: 8,
        memory: 56.0,
        maxDiskCount: 32,
        resourceDiskSize: 112.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 0.598,
        pricePerCore: 0.07475,
        usageLimit: 100,
        availableUsage: 60,
    },
    {
        name: "Standard_D13_v2",
        sku: "D13_v2",
        type: "Memory",
        tier: "Standard",
        cores: 8,
        memory: 56.0,
        maxDiskCount: 32,
        resourceDiskSize: 400.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 0.598,
        pricePerCore: 0.07475,
        usageLimit: 100,
        availableUsage: 76,
    },
    {
        name: "Standard_DS12_v2",
        sku: "DS12_v2",
        type: "Memory",
        tier: "Standard",
        cores: 4,
        memory: 28.0,
        maxDiskCount: 16,
        resourceDiskSize: 56.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 0.299,
        pricePerCore: 0.07475,
        usageLimit: 100,
        availableUsage: 60,
    },
    {
        name: "Standard_M128s",
        sku: "M128s",
        type: "Memory",
        tier: "Standard",
        cores: 128,
        memory: 2000.0,
        maxDiskCount: 64,
        resourceDiskSize: 4000.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 13.338,
        pricePerCore: 0.104203125,
        usageLimit: 0,
        availableUsage: 0,
    },
    {
        name: "Standard_G4",
        sku: "G4",
        type: "Memory",
        tier: "Standard",
        cores: 16,
        memory: 224.0,
        maxDiskCount: 64,
        resourceDiskSize: 3072.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 3.922,
        pricePerCore: 0.245125,
        usageLimit: 100,
        availableUsage: 100,
    },
    {
        name: "Standard_D16s_v3",
        sku: "D16s_v3",
        type: "General",
        tier: "Standard",
        cores: 16,
        memory: 64.0,
        maxDiskCount: 32,
        resourceDiskSize: 128.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 0.768,
        pricePerCore: 0.048,
        usageLimit: 300,
        availableUsage: 278,
    },
    {
        name: "Standard_D1_v2",
        sku: "D1_v2",
        type: "General",
        tier: "Standard",
        cores: 1,
        memory: 3.5,
        maxDiskCount: 4,
        resourceDiskSize: 50.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 0.057,
        pricePerCore: 0.057,
        usageLimit: 100,
        availableUsage: 76,
    },
    {
        name: "Standard_A7",
        sku: "A7",
        type: "General",
        tier: "Standard",
        cores: 8,
        memory: 56.0,
        maxDiskCount: 16,
        resourceDiskSize: 605.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 0.88,
        pricePerCore: 0.11,
        usageLimit: 100,
        availableUsage: 94,
    },
    {
        name: "Standard_D32_v3",
        sku: "D32_v3",
        type: "General",
        tier: "Standard",
        cores: 32,
        memory: 128.0,
        maxDiskCount: 32,
        resourceDiskSize: 800.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 1.536,
        pricePerCore: 0.048,
        usageLimit: 10000,
        availableUsage: 5822,
    },
    {
        name: "Standard_GS2",
        sku: "GS2",
        type: "Memory",
        tier: "Standard",
        cores: 4,
        memory: 56.0,
        maxDiskCount: 16,
        resourceDiskSize: 112.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 0.981,
        pricePerCore: 0.24525,
        usageLimit: 100,
        availableUsage: 100,
    },
    {
        name: "Standard_M128m",
        sku: "M128m",
        type: "Memory",
        tier: "Standard",
        cores: 128,
        memory: 3800.0,
        maxDiskCount: 64,
        resourceDiskSize: 16000.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 26.688,
        pricePerCore: 0.2085,
        usageLimit: 0,
        availableUsage: 0,
    },
    {
        name: "Standard_M32-8ms",
        sku: "M32-8ms",
        type: "Memory",
        tier: "Standard",
        cores: 32,
        memory: 875.0,
        maxDiskCount: 32,
        resourceDiskSize: 1000.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 6.146,
        pricePerCore: 0.1920625,
        usageLimit: 0,
        availableUsage: 0,
    },
    {
        name: "Standard_H16r",
        sku: "H16r",
        type: "HPC",
        tier: "Standard",
        cores: 16,
        memory: 112.0,
        maxDiskCount: 64,
        resourceDiskSize: 2000.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 1.75,
        pricePerCore: 0.109375,
        usageLimit: 8,
        availableUsage: 8,
    },
    {
        name: "Standard_ND12s",
        sku: "ND12s",
        type: "GPU",
        tier: "Standard",
        cores: 12,
        memory: 224.0,
        maxDiskCount: 24,
        resourceDiskSize: 672.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 4.14,
        pricePerCore: 0.345,
        usageLimit: 0,
        availableUsage: 0,
    },
    {
        name: "Standard_E4-2s_v3",
        sku: "E4-2s_v3",
        type: "Memory",
        tier: "Standard",
        cores: 4,
        memory: 32.0,
        maxDiskCount: 8,
        resourceDiskSize: 64.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 0.252,
        pricePerCore: 0.063,
        usageLimit: 300,
        availableUsage: 300,
    },
    {
        name: "Standard_L8s",
        sku: "L8s",
        type: "Storage",
        tier: "Standard",
        cores: 8,
        memory: 64.0,
        maxDiskCount: 32,
        resourceDiskSize: 1388.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 0.624,
        pricePerCore: 0.078,
        usageLimit: 100,
        availableUsage: 100,
    },
    {
        name: "Standard_H16",
        sku: "H16",
        type: "HPC",
        tier: "Standard",
        cores: 16,
        memory: 112.0,
        maxDiskCount: 64,
        resourceDiskSize: 2000.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 1.591,
        pricePerCore: 0.0994375,
        usageLimit: 8,
        availableUsage: 8,
    },
    {
        name: "Standard_NC6s_v3",
        sku: "NC6s_v3",
        type: "GPU",
        tier: "Standard",
        cores: 6,
        memory: 112.0,
        maxDiskCount: 12,
        resourceDiskSize: 336.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 3.06,
        pricePerCore: 0.51,
        usageLimit: 0,
        availableUsage: 0,
    },
    {
        name: "Standard_M64ms",
        sku: "M64ms",
        type: "Memory",
        tier: "Standard",
        cores: 64,
        memory: 1750.0,
        maxDiskCount: 64,
        resourceDiskSize: 2000.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 10.337,
        pricePerCore: 0.161515625,
        usageLimit: 0,
        availableUsage: 0,
    },
    {
        name: "Standard_D64s_v3",
        sku: "D64s_v3",
        type: "General",
        tier: "Standard",
        cores: 64,
        memory: 256.0,
        maxDiskCount: 32,
        resourceDiskSize: 512.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 3.072,
        pricePerCore: 0.048,
        usageLimit: 300,
        availableUsage: 278,
    },
    {
        name: "Standard_E64-16s_v3",
        sku: "E64-16s_v3",
        type: "Memory",
        tier: "Standard",
        cores: 64,
        memory: 432.0,
        maxDiskCount: 32,
        resourceDiskSize: 864.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 3.629,
        pricePerCore: 0.056703125,
        usageLimit: 300,
        availableUsage: 300,
    },
    {
        name: "Standard_M8-4ms",
        sku: "M8-4ms",
        type: "Memory",
        tier: "Standard",
        cores: 8,
        memory: 218.75,
        maxDiskCount: 8,
        resourceDiskSize: 250.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 1.5365,
        pricePerCore: 0.1920625,
        usageLimit: 0,
        availableUsage: 0,
    },
    {
        name: "Standard_F4s_v2",
        sku: "F4s_v2",
        type: "Compute",
        tier: "Standard",
        cores: 4,
        memory: 8.0,
        maxDiskCount: 8,
        resourceDiskSize: 32.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 0.17,
        pricePerCore: 0.0425,
        usageLimit: 100,
        availableUsage: 100,
    },
    {
        name: "Standard_L32s",
        sku: "L32s",
        type: "Storage",
        tier: "Standard",
        cores: 32,
        memory: 256.0,
        maxDiskCount: 64,
        resourceDiskSize: 5630.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 2.496,
        pricePerCore: 0.078,
        usageLimit: 100,
        availableUsage: 100,
    },
    {
        name: "Standard_F2s",
        sku: "F2s",
        type: "Compute",
        tier: "Standard",
        cores: 2,
        memory: 4.0,
        maxDiskCount: 8,
        resourceDiskSize: 8.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 0.099,
        pricePerCore: 0.0495,
        usageLimit: 100,
        availableUsage: 100,
    },
    {
        name: "Standard_D8s_v3",
        sku: "D8s_v3",
        type: "General",
        tier: "Standard",
        cores: 8,
        memory: 32.0,
        maxDiskCount: 16,
        resourceDiskSize: 64.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 0.384,
        pricePerCore: 0.048,
        usageLimit: 300,
        availableUsage: 278,
    },
    {
        name: "Standard_NC24s_v2",
        sku: "NC24s_v2",
        type: "GPU",
        tier: "Standard",
        cores: 24,
        memory: 448.0,
        maxDiskCount: 32,
        resourceDiskSize: 1344.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 8.28,
        pricePerCore: 0.345,
        usageLimit: 0,
        availableUsage: 0,
    },
    {
        name: "Standard_A2",
        sku: "A2",
        type: "General",
        tier: "Standard",
        cores: 2,
        memory: 3.5,
        maxDiskCount: 4,
        resourceDiskSize: 135.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 0.101,
        pricePerCore: 0.0505,
        usageLimit: 100,
        availableUsage: 94,
    },
    {
        name: "Standard_L80s_v2",
        sku: "L80s_v2",
        type: "Storage",
        tier: "Standard",
        cores: 80,
        memory: 640.0,
        maxDiskCount: 32,
        resourceDiskSize: 17695.1,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 6.24,
        pricePerCore: 0.078,
        usageLimit: 100,
        availableUsage: 100,
    },
    {
        name: "Standard_GS4-8",
        sku: "GS4-8",
        type: "Memory",
        tier: "Standard",
        cores: 16,
        memory: 224.0,
        maxDiskCount: 64,
        resourceDiskSize: 448.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 3.922,
        pricePerCore: 0.245125,
        usageLimit: 100,
        availableUsage: 100,
    },
    {
        name: "Standard_NC6",
        sku: "NC6",
        type: "GPU",
        tier: "Standard",
        cores: 6,
        memory: 56.0,
        maxDiskCount: 24,
        resourceDiskSize: 380.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 0.9,
        pricePerCore: 0.15,
        usageLimit: 48,
        availableUsage: 48,
    },
    {
        name: "Standard_M128ms",
        sku: "M128ms",
        type: "Memory",
        tier: "Standard",
        cores: 128,
        memory: 3800.0,
        maxDiskCount: 64,
        resourceDiskSize: 4000.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 26.688,
        pricePerCore: 0.2085,
        usageLimit: 0,
        availableUsage: 0,
    },
    {
        name: "Standard_E8_v3",
        sku: "E8_v3",
        type: "Memory",
        tier: "Standard",
        cores: 8,
        memory: 64.0,
        maxDiskCount: 16,
        resourceDiskSize: 200.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 0.504,
        pricePerCore: 0.063,
        usageLimit: 10000,
        availableUsage: 10000,
    },
    {
        name: "Standard_M128-32ms",
        sku: "M128-32ms",
        type: "Memory",
        tier: "Standard",
        cores: 128,
        memory: 3800.0,
        maxDiskCount: 64,
        resourceDiskSize: 4000.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 26.688,
        pricePerCore: 0.2085,
        usageLimit: 0,
        availableUsage: 0,
    },
    {
        name: "Standard_M8ms",
        sku: "M8ms",
        type: "Memory",
        tier: "Standard",
        cores: 8,
        memory: 218.75,
        maxDiskCount: 8,
        resourceDiskSize: 250.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 1.5365,
        pricePerCore: 0.1920625,
        usageLimit: 0,
        availableUsage: 0,
    },
    {
        name: "Standard_ND24s",
        sku: "ND24s",
        type: "GPU",
        tier: "Standard",
        cores: 24,
        memory: 448.0,
        maxDiskCount: 32,
        resourceDiskSize: 1344.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 8.28,
        pricePerCore: 0.345,
        usageLimit: 0,
        availableUsage: 0,
    },
    {
        name: "Standard_A1_v2",
        sku: "A1_v2",
        type: "General",
        tier: "Standard",
        cores: 1,
        memory: 2.0,
        maxDiskCount: 2,
        resourceDiskSize: 10.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 0.036,
        pricePerCore: 0.036,
        usageLimit: 100,
        availableUsage: 100,
    },
    {
        name: "Standard_ND24rs",
        sku: "ND24rs",
        type: "GPU",
        tier: "Standard",
        cores: 24,
        memory: 448.0,
        maxDiskCount: 32,
        resourceDiskSize: 1344.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 9.108,
        pricePerCore: 0.3795,
        usageLimit: 0,
        availableUsage: 0,
    },
    {
        name: "Basic_A2",
        sku: "A2",
        type: "General",
        tier: "Basic",
        cores: 2,
        memory: 3.5,
        maxDiskCount: 4,
        resourceDiskSize: 60.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 0.068,
        pricePerCore: 0.034,
        usageLimit: 100,
        availableUsage: 100,
    },
    {
        name: "Standard_L16s",
        sku: "L16s",
        type: "Storage",
        tier: "Standard",
        cores: 16,
        memory: 128.0,
        maxDiskCount: 64,
        resourceDiskSize: 2807.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 1.248,
        pricePerCore: 0.078,
        usageLimit: 100,
        availableUsage: 100,
    },
    {
        name: "Standard_F64s_v2",
        sku: "F64s_v2",
        type: "Compute",
        tier: "Standard",
        cores: 64,
        memory: 128.0,
        maxDiskCount: 32,
        resourceDiskSize: 512.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 2.72,
        pricePerCore: 0.0425,
        usageLimit: 100,
        availableUsage: 100,
    },
    {
        name: "Standard_F8s",
        sku: "F8s",
        type: "Compute",
        tier: "Standard",
        cores: 8,
        memory: 16.0,
        maxDiskCount: 32,
        resourceDiskSize: 32.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 0.398,
        pricePerCore: 0.04975,
        usageLimit: 100,
        availableUsage: 100,
    },
    {
        name: "Standard_DS12-2_v2",
        sku: "DS12-2_v2",
        type: "General",
        tier: "Standard",
        cores: 4,
        memory: 28.0,
        maxDiskCount: 16,
        resourceDiskSize: 56.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 0.299,
        pricePerCore: 0.07475,
        usageLimit: 100,
        availableUsage: 60,
    },
    {
        name: "Standard_G2",
        sku: "G2",
        type: "Memory",
        tier: "Standard",
        cores: 4,
        memory: 56.0,
        maxDiskCount: 16,
        resourceDiskSize: 768.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 0.981,
        pricePerCore: 0.24525,
        usageLimit: 100,
        availableUsage: 100,
    },
    {
        name: "Standard_F8s_v2",
        sku: "F8s_v2",
        type: "Compute",
        tier: "Standard",
        cores: 8,
        memory: 16.0,
        maxDiskCount: 16,
        resourceDiskSize: 64.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 0.34,
        pricePerCore: 0.0425,
        usageLimit: 100,
        availableUsage: 100,
    },
    {
        name: "Basic_A1",
        sku: "A1",
        type: "General",
        tier: "Basic",
        cores: 1,
        memory: 1.75,
        maxDiskCount: 2,
        resourceDiskSize: 40.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 0.023,
        pricePerCore: 0.023,
        usageLimit: 100,
        availableUsage: 100,
    },
    {
        name: "Standard_DS4_v2",
        sku: "DS4_v2",
        type: "General",
        tier: "Standard",
        cores: 8,
        memory: 28.0,
        maxDiskCount: 32,
        resourceDiskSize: 56.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 0.458,
        pricePerCore: 0.05725,
        usageLimit: 100,
        availableUsage: 60,
    },
    {
        name: "Standard_D4_v2",
        sku: "D4_v2",
        type: "General",
        tier: "Standard",
        cores: 8,
        memory: 28.0,
        maxDiskCount: 32,
        resourceDiskSize: 400.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 0.458,
        pricePerCore: 0.05725,
        usageLimit: 100,
        availableUsage: 76,
    },
    {
        name: "Standard_GS3",
        sku: "GS3",
        type: "Memory",
        tier: "Standard",
        cores: 8,
        memory: 112.0,
        maxDiskCount: 32,
        resourceDiskSize: 224.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 1.961,
        pricePerCore: 0.245125,
        usageLimit: 100,
        availableUsage: 100,
    },
    {
        name: "Standard_D64_v3",
        sku: "D64_v3",
        type: "General",
        tier: "Standard",
        cores: 64,
        memory: 256.0,
        maxDiskCount: 32,
        resourceDiskSize: 1600.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 3.072,
        pricePerCore: 0.048,
        usageLimit: 10000,
        availableUsage: 5822,
    },
    {
        name: "Standard_F4s",
        sku: "F4s",
        type: "Compute",
        tier: "Standard",
        cores: 4,
        memory: 8.0,
        maxDiskCount: 16,
        resourceDiskSize: 16.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 0.199,
        pricePerCore: 0.04975,
        usageLimit: 100,
        availableUsage: 100,
    },
    {
        name: "Standard_E20_v3",
        sku: "E20_v3",
        type: "Memory",
        tier: "Standard",
        cores: 20,
        memory: 160.0,
        maxDiskCount: 32,
        resourceDiskSize: 500.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 1.26,
        pricePerCore: 0.063,
        usageLimit: 10000,
        availableUsage: 10000,
    },
    {
        name: "Standard_M16-8ms",
        sku: "M16-8ms",
        type: "Memory",
        tier: "Standard",
        cores: 16,
        memory: 437.5,
        maxDiskCount: 16,
        resourceDiskSize: 500.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 3.073,
        pricePerCore: 0.1920625,
        usageLimit: 0,
        availableUsage: 0,
    },
    {
        name: "Standard_DS11_v2",
        sku: "DS11_v2",
        type: "Memory",
        tier: "Standard",
        cores: 2,
        memory: 14.0,
        maxDiskCount: 8,
        resourceDiskSize: 28.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 0.149,
        pricePerCore: 0.0745,
        usageLimit: 100,
        availableUsage: 60,
    },
    {
        name: "Standard_DS14-4_v2",
        sku: "DS14-4_v2",
        type: "General",
        tier: "Standard",
        cores: 16,
        memory: 112.0,
        maxDiskCount: 64,
        resourceDiskSize: 224.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 1.196,
        pricePerCore: 0.07475,
        usageLimit: 100,
        availableUsage: 60,
    },
    {
        name: "Standard_F1",
        sku: "F1",
        type: "Compute",
        tier: "Standard",
        cores: 1,
        memory: 2.0,
        maxDiskCount: 4,
        resourceDiskSize: 16.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 0.05,
        pricePerCore: 0.05,
        usageLimit: 100,
        availableUsage: 100,
    },
    {
        name: "Standard_M128",
        sku: "M128",
        type: "Memory",
        tier: "Standard",
        cores: 128,
        memory: 2000.0,
        maxDiskCount: 64,
        resourceDiskSize: 16000.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 13.338,
        pricePerCore: 0.104203125,
        usageLimit: 0,
        availableUsage: 0,
    },
    {
        name: "Standard_GS5-16",
        sku: "GS5-16",
        type: "Memory",
        tier: "Standard",
        cores: 32,
        memory: 448.0,
        maxDiskCount: 64,
        resourceDiskSize: 896.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 7.843,
        pricePerCore: 0.24509375,
        usageLimit: 100,
        availableUsage: 100,
    },
    {
        name: "Standard_E20s_v3",
        sku: "E20s_v3",
        type: "Memory",
        tier: "Standard",
        cores: 20,
        memory: 160.0,
        maxDiskCount: 32,
        resourceDiskSize: 320.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 1.26,
        pricePerCore: 0.063,
        usageLimit: 300,
        availableUsage: 300,
    },
    {
        name: "Standard_D3_v2",
        sku: "D3_v2",
        type: "General",
        tier: "Standard",
        cores: 4,
        memory: 14.0,
        maxDiskCount: 16,
        resourceDiskSize: 200.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 0.229,
        pricePerCore: 0.05725,
        usageLimit: 100,
        availableUsage: 76,
    },
    {
        name: "Standard_E8-2s_v3",
        sku: "E8-2s_v3",
        type: "Memory",
        tier: "Standard",
        cores: 8,
        memory: 64.0,
        maxDiskCount: 16,
        resourceDiskSize: 128.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 0.504,
        pricePerCore: 0.063,
        usageLimit: 300,
        availableUsage: 300,
    },
    {
        name: "Standard_M16-4ms",
        sku: "M16-4ms",
        type: "Memory",
        tier: "Standard",
        cores: 16,
        memory: 437.5,
        maxDiskCount: 16,
        resourceDiskSize: 500.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 3.073,
        pricePerCore: 0.1920625,
        usageLimit: 0,
        availableUsage: 0,
    },
    {
        name: "Standard_E2s_v3",
        sku: "E2s_v3",
        type: "Memory",
        tier: "Standard",
        cores: 2,
        memory: 16.0,
        maxDiskCount: 4,
        resourceDiskSize: 32.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 0.126,
        pricePerCore: 0.063,
        usageLimit: 300,
        availableUsage: 300,
    },
    {
        name: "Standard_NC12s_v2",
        sku: "NC12s_v2",
        type: "GPU",
        tier: "Standard",
        cores: 12,
        memory: 224.0,
        maxDiskCount: 24,
        resourceDiskSize: 672.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 4.14,
        pricePerCore: 0.345,
        usageLimit: 0,
        availableUsage: 0,
    },
    {
        name: "Standard_G5",
        sku: "G5",
        type: "Memory",
        tier: "Standard",
        cores: 32,
        memory: 448.0,
        maxDiskCount: 64,
        resourceDiskSize: 6144.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 7.843,
        pricePerCore: 0.24509375,
        usageLimit: 100,
        availableUsage: 100,
    },
    {
        name: "Standard_M64m",
        sku: "M64m",
        type: "Memory",
        tier: "Standard",
        cores: 64,
        memory: 1750.0,
        maxDiskCount: 64,
        resourceDiskSize: 8000.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 10.337,
        pricePerCore: 0.161515625,
        usageLimit: 0,
        availableUsage: 0,
    },
    {
        name: "Standard_D2_v3",
        sku: "D2_v3",
        type: "General",
        tier: "Standard",
        cores: 2,
        memory: 8.0,
        maxDiskCount: 4,
        resourceDiskSize: 50.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 0.096,
        pricePerCore: 0.048,
        usageLimit: 10000,
        availableUsage: 5822,
    },
    {
        name: "Standard_NC12",
        sku: "NC12",
        type: "GPU",
        tier: "Standard",
        cores: 12,
        memory: 112.0,
        maxDiskCount: 48,
        resourceDiskSize: 680.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 1.8,
        pricePerCore: 0.15,
        usageLimit: 48,
        availableUsage: 48,
    },
    {
        name: "Standard_M64-32ms",
        sku: "M64-32ms",
        type: "Memory",
        tier: "Standard",
        cores: 64,
        memory: 1750.0,
        maxDiskCount: 64,
        resourceDiskSize: 2000.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 10.337,
        pricePerCore: 0.161515625,
        usageLimit: 0,
        availableUsage: 0,
    },
    {
        name: "Standard_D5_v2",
        sku: "D5_v2",
        type: "General",
        tier: "Standard",
        cores: 16,
        memory: 56.0,
        maxDiskCount: 64,
        resourceDiskSize: 800.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 0.916,
        pricePerCore: 0.05725,
        usageLimit: 100,
        availableUsage: 76,
    },
    {
        name: "Standard_E32-8s_v3",
        sku: "E32-8s_v3",
        type: "Memory",
        tier: "Standard",
        cores: 32,
        memory: 256.0,
        maxDiskCount: 32,
        resourceDiskSize: 512.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 2.016,
        pricePerCore: 0.063,
        usageLimit: 300,
        availableUsage: 300,
    },
    {
        name: "Standard_A6",
        sku: "A6",
        type: "General",
        tier: "Standard",
        cores: 4,
        memory: 28.0,
        maxDiskCount: 8,
        resourceDiskSize: 285.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 0.44,
        pricePerCore: 0.11,
        usageLimit: 100,
        availableUsage: 94,
    },
    {
        name: "Basic_A4",
        sku: "A4",
        type: "General",
        tier: "Basic",
        cores: 8,
        memory: 14.0,
        maxDiskCount: 16,
        resourceDiskSize: 240.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 0.352,
        pricePerCore: 0.044,
        usageLimit: 100,
        availableUsage: 100,
    },
    {
        name: "Standard_D16_v3",
        sku: "D16_v3",
        type: "General",
        tier: "Standard",
        cores: 16,
        memory: 64.1,
        maxDiskCount: 32,
        resourceDiskSize: 400.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 0.768,
        pricePerCore: 0.048,
        usageLimit: 10000,
        availableUsage: 5822,
    },
    {
        name: "Standard_H8m",
        sku: "H8m",
        type: "HPC",
        tier: "Standard",
        cores: 8,
        memory: 112.0,
        maxDiskCount: 32,
        resourceDiskSize: 1000.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 1.066,
        pricePerCore: 0.13325,
        usageLimit: 8,
        availableUsage: 8,
    },
    {
        name: "Standard_L4s",
        sku: "L4s",
        type: "Storage",
        tier: "Standard",
        cores: 4,
        memory: 32.0,
        maxDiskCount: 16,
        resourceDiskSize: 678.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 0.312,
        pricePerCore: 0.078,
        usageLimit: 100,
        availableUsage: 100,
    },
    {
        name: "Standard_M16ms",
        sku: "M16ms",
        type: "Memory",
        tier: "Standard",
        cores: 16,
        memory: 437.5,
        maxDiskCount: 16,
        resourceDiskSize: 500.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 3.073,
        pricePerCore: 0.1920625,
        usageLimit: 0,
        availableUsage: 0,
    },
    {
        name: "Standard_D2_v2",
        sku: "D2_v2",
        type: "General",
        tier: "Standard",
        cores: 2,
        memory: 7.0,
        maxDiskCount: 8,
        resourceDiskSize: 100.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 0.114,
        pricePerCore: 0.057,
        usageLimit: 100,
        availableUsage: 76,
    },
    {
        name: "Standard_E32_v3",
        sku: "E32_v3",
        type: "Memory",
        tier: "Standard",
        cores: 32,
        memory: 256.0,
        maxDiskCount: 32,
        resourceDiskSize: 800.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 2.016,
        pricePerCore: 0.063,
        usageLimit: 10000,
        availableUsage: 10000,
    },
    {
        name: "Standard_A2_v2",
        sku: "A2_v2",
        type: "General",
        tier: "Standard",
        cores: 2,
        memory: 4.0,
        maxDiskCount: 4,
        resourceDiskSize: 20.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 0.076,
        pricePerCore: 0.038,
        usageLimit: 100,
        availableUsage: 100,
    },
    {
        name: "Standard_H8",
        sku: "H8",
        type: "HPC",
        tier: "Standard",
        cores: 8,
        memory: 56.0,
        maxDiskCount: 32,
        resourceDiskSize: 1000.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 0.796,
        pricePerCore: 0.0995,
        usageLimit: 8,
        availableUsage: 8,
    },
    {
        name: "Standard_M32ts",
        sku: "M32ts",
        type: "Memory",
        tier: "Standard",
        cores: 32,
        memory: 192.0,
        maxDiskCount: 32,
        resourceDiskSize: 1000.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 2.707,
        pricePerCore: 0.08459375,
        usageLimit: 0,
        availableUsage: 0,
    },
    {
        name: "Standard_NV12",
        sku: "NV12",
        type: "GPU",
        tier: "Standard",
        cores: 12,
        memory: 112.0,
        maxDiskCount: 48,
        resourceDiskSize: 680.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 2.185,
        pricePerCore: 0.18208333333333335,
        usageLimit: 24,
        availableUsage: 24,
    },
    {
        name: "Standard_G3",
        sku: "G3",
        type: "Memory",
        tier: "Standard",
        cores: 8,
        memory: 112.0,
        maxDiskCount: 32,
        resourceDiskSize: 1536.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 1.961,
        pricePerCore: 0.245125,
        usageLimit: 100,
        availableUsage: 100,
    },
    {
        name: "Standard_GS5",
        sku: "GS5",
        type: "Memory",
        tier: "Standard",
        cores: 32,
        memory: 448.0,
        maxDiskCount: 64,
        resourceDiskSize: 896.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 7.843,
        pricePerCore: 0.24509375,
        usageLimit: 100,
        availableUsage: 100,
    },
    {
        name: "Standard_M128-64ms",
        sku: "M128-64ms",
        type: "Memory",
        tier: "Standard",
        cores: 128,
        memory: 3800.0,
        maxDiskCount: 64,
        resourceDiskSize: 4000.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 26.688,
        pricePerCore: 0.2085,
        usageLimit: 0,
        availableUsage: 0,
    },
    {
        name: "Standard_A5",
        sku: "A5",
        type: "General",
        tier: "Standard",
        cores: 2,
        memory: 14.0,
        maxDiskCount: 4,
        resourceDiskSize: 135.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 0.22,
        pricePerCore: 0.11,
        usageLimit: 100,
        availableUsage: 94,
    },
    {
        name: "Standard_GS1",
        sku: "GS1",
        type: "Memory",
        tier: "Standard",
        cores: 2,
        memory: 28.0,
        maxDiskCount: 8,
        resourceDiskSize: 56.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 0.49,
        pricePerCore: 0.245,
        usageLimit: 100,
        availableUsage: 100,
    },
    {
        name: "Standard_M64ls",
        sku: "M64ls",
        type: "Memory",
        tier: "Standard",
        cores: 64,
        memory: 512.0,
        maxDiskCount: 64,
        resourceDiskSize: 2000.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 5.415,
        pricePerCore: 0.084609375,
        usageLimit: 0,
        availableUsage: 0,
    },
    {
        name: "Standard_NC24",
        sku: "NC24",
        type: "GPU",
        tier: "Standard",
        cores: 24,
        memory: 224.0,
        maxDiskCount: 64,
        resourceDiskSize: 1440.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 3.6,
        pricePerCore: 0.15,
        usageLimit: 48,
        availableUsage: 48,
    },
    {
        name: "Standard_NC24rs_v3",
        sku: "NC24rs_v3",
        type: "GPU",
        tier: "Standard",
        cores: 24,
        memory: 448.0,
        maxDiskCount: 32,
        resourceDiskSize: 1344.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 13.464,
        pricePerCore: 0.561,
        usageLimit: 0,
        availableUsage: 0,
    },
    {
        name: "Standard_E16-4s_v3",
        sku: "E16-4s_v3",
        type: "Memory",
        tier: "Standard",
        cores: 16,
        memory: 128.0,
        maxDiskCount: 32,
        resourceDiskSize: 256.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 1.008,
        pricePerCore: 0.063,
        usageLimit: 300,
        availableUsage: 300,
    },
    {
        name: "Standard_A8m_v2",
        sku: "A8m_v2",
        type: "General",
        tier: "Standard",
        cores: 8,
        memory: 64.0,
        maxDiskCount: 16,
        resourceDiskSize: 80.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 0.437,
        pricePerCore: 0.054625,
        usageLimit: 100,
        availableUsage: 100,
    },
    {
        name: "Standard_H16m",
        sku: "H16m",
        type: "HPC",
        tier: "Standard",
        cores: 16,
        memory: 224.0,
        maxDiskCount: 64,
        resourceDiskSize: 2000.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 2.132,
        pricePerCore: 0.13325,
        usageLimit: 8,
        availableUsage: 8,
    },
    {
        name: "Standard_F16s_v2",
        sku: "F16s_v2",
        type: "Compute",
        tier: "Standard",
        cores: 16,
        memory: 32.0,
        maxDiskCount: 32,
        resourceDiskSize: 128.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 0.68,
        pricePerCore: 0.0425,
        usageLimit: 100,
        availableUsage: 100,
    },
    {
        name: "Standard_A8_v2",
        sku: "A8_v2",
        type: "General",
        tier: "Standard",
        cores: 8,
        memory: 16.0,
        maxDiskCount: 16,
        resourceDiskSize: 80.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 0.333,
        pricePerCore: 0.041625,
        usageLimit: 100,
        availableUsage: 100,
    },
    {
        name: "Standard_DS2_v2",
        sku: "DS2_v2",
        type: "General",
        tier: "Standard",
        cores: 2,
        memory: 7.0,
        maxDiskCount: 8,
        resourceDiskSize: 14.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 0.114,
        pricePerCore: 0.057,
        usageLimit: 100,
        availableUsage: 60,
    },
    {
        name: "Standard_HC44rs",
        sku: "HC44rs",
        type: "HPC",
        tier: "Standard",
        cores: 44,
        memory: 327.83,
        maxDiskCount: 4,
        resourceDiskSize: 700.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 1.584,
        pricePerCore: 0.036000000000000004,
        usageLimit: 8800,
        availableUsage: 8756,
    },
    {
        name: "Standard_E8s_v3",
        sku: "E8s_v3",
        type: "Memory",
        tier: "Standard",
        cores: 8,
        memory: 64.0,
        maxDiskCount: 16,
        resourceDiskSize: 128.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 0.504,
        pricePerCore: 0.063,
        usageLimit: 300,
        availableUsage: 300,
    },
    {
        name: "Standard_E4_v3",
        sku: "E4_v3",
        type: "Memory",
        tier: "Standard",
        cores: 4,
        memory: 32.0,
        maxDiskCount: 8,
        resourceDiskSize: 100.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 0.252,
        pricePerCore: 0.063,
        usageLimit: 10000,
        availableUsage: 10000,
    },
    {
        name: "Standard_A4_v2",
        sku: "A4_v2",
        type: "General",
        tier: "Standard",
        cores: 4,
        memory: 8.0,
        maxDiskCount: 8,
        resourceDiskSize: 40.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 0.159,
        pricePerCore: 0.03975,
        usageLimit: 100,
        availableUsage: 100,
    },
    {
        name: "Standard_A4m_v2",
        sku: "A4m_v2",
        type: "General",
        tier: "Standard",
        cores: 4,
        memory: 32.0,
        maxDiskCount: 8,
        resourceDiskSize: 40.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 0.208,
        pricePerCore: 0.052,
        usageLimit: 100,
        availableUsage: 100,
    },
    {
        name: "Standard_NV24",
        sku: "NV24",
        type: "GPU",
        tier: "Standard",
        cores: 24,
        memory: 224.0,
        maxDiskCount: 64,
        resourceDiskSize: 1440.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 4.37,
        pricePerCore: 0.18208333333333335,
        usageLimit: 24,
        availableUsage: 24,
    },
    {
        name: "Standard_E64-32s_v3",
        sku: "E64-32s_v3",
        type: "Memory",
        tier: "Standard",
        cores: 64,
        memory: 432.0,
        maxDiskCount: 32,
        resourceDiskSize: 864.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 3.629,
        pricePerCore: 0.056703125,
        usageLimit: 300,
        availableUsage: 300,
    },
    {
        name: "Standard_DS3_v2",
        sku: "DS3_v2",
        type: "General",
        tier: "Standard",
        cores: 4,
        memory: 14.0,
        maxDiskCount: 16,
        resourceDiskSize: 28.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 0.229,
        pricePerCore: 0.05725,
        usageLimit: 100,
        availableUsage: 60,
    },
    {
        name: "Standard_F16",
        sku: "F16",
        type: "Compute",
        tier: "Standard",
        cores: 16,
        memory: 32.0,
        maxDiskCount: 64,
        resourceDiskSize: 256.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 0.796,
        pricePerCore: 0.04975,
        usageLimit: 100,
        availableUsage: 100,
    },
    {
        name: "Standard_GS5-8",
        sku: "GS5-8",
        type: "Memory",
        tier: "Standard",
        cores: 32,
        memory: 448.0,
        maxDiskCount: 64,
        resourceDiskSize: 896.0,
        osDiskSize: 1023.0,
        ssd: true,
        lowPriorityCapable: true,
        price: 7.843,
        pricePerCore: 0.24509375,
        usageLimit: 100,
        availableUsage: 100,
    },
    {
        name: "Standard_D8_v3",
        sku: "D8_v3",
        type: "General",
        tier: "Standard",
        cores: 8,
        memory: 32.0,
        maxDiskCount: 16,
        resourceDiskSize: 200.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 0.384,
        pricePerCore: 0.048,
        usageLimit: 10000,
        availableUsage: 5822,
    },
    {
        name: "Standard_H16mr",
        sku: "H16mr",
        type: "HPC",
        tier: "Standard",
        cores: 16,
        memory: 224.0,
        maxDiskCount: 64,
        resourceDiskSize: 2000.0,
        osDiskSize: 1023.0,
        ssd: false,
        lowPriorityCapable: true,
        price: 2.345,
        pricePerCore: 0.1465625,
        usageLimit: 8,
        availableUsage: 8,
    }
];

export default MachineTypes;